/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Sistema de Biblioteca Escolar API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface SuccessResponse {
  success: boolean;
  message?: string;
}

export type LoginRequestRole =
  (typeof LoginRequestRole)[keyof typeof LoginRequestRole];

export const LoginRequestRole = {
  adm: "adm",
  aluno: "aluno",
} as const;

export interface LoginRequest {
  email: string;
  password: string;
  role: LoginRequestRole;
}

export interface User {
  id: number;
  name: string;
  email: string;
  role: string;
  matricula?: string | null;
  createdAt?: string | null;
}

export interface LoginResponse {
  user: User;
  token: string;
}

export interface CreateUserRequest {
  name: string;
  email: string;
  password: string;
  role?: string;
  matricula?: string | null;
}

export interface UpdateUserRequest {
  name?: string;
  email?: string;
  matricula?: string | null;
}

export interface Book {
  id: number;
  title: string;
  author: string;
  isbn?: string | null;
  category?: string | null;
  description?: string | null;
  year?: number | null;
  publisher?: string | null;
  quantity: number;
  available: number;
  createdAt?: string | null;
}

export interface CreateBookRequest {
  title: string;
  author: string;
  isbn?: string | null;
  category?: string | null;
  description?: string | null;
  year?: number | null;
  publisher?: string | null;
  quantity: number;
  available: number;
}

export interface Loan {
  id: number;
  userId: number;
  bookId: number;
  loanDate?: string | null;
  pickupDate?: string | null;
  dueDate: string;
  returnDate?: string | null;
  status: string;
  fine?: string | null;
  finePaid?: boolean | null;
  user?: User | null;
  book?: Book | null;
}

export interface CreateLoanRequest {
  userId?: number | null;
  bookId: number;
  pickupDate?: string | null;
  dueDate: string;
}

export interface UpdateLoanRequest {
  status?: string;
  pickupDate?: string | null;
  returnDate?: string | null;
  fine?: string | null;
  finePaid?: boolean | null;
}
