/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Sistema de Biblioteca Escolar API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Login
 */
export const LoginBody = zod.object({
  email: zod.string(),
  password: zod.string(),
  role: zod.enum(["adm", "aluno"]),
});

export const LoginResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    name: zod.string(),
    email: zod.string(),
    role: zod.string(),
    matricula: zod.string().nullish(),
    createdAt: zod.string().nullish(),
  }),
  token: zod.string(),
});

/**
 * @summary Logout
 */
export const LogoutResponse = zod.object({
  success: zod.boolean(),
  message: zod.string().optional(),
});

/**
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  role: zod.string(),
  matricula: zod.string().nullish(),
  createdAt: zod.string().nullish(),
});

/**
 * @summary List all books
 */
export const ListBooksResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  author: zod.string(),
  isbn: zod.string().nullish(),
  category: zod.string().nullish(),
  description: zod.string().nullish(),
  year: zod.number().nullish(),
  publisher: zod.string().nullish(),
  quantity: zod.number(),
  available: zod.number(),
  createdAt: zod.string().nullish(),
});
export const ListBooksResponse = zod.array(ListBooksResponseItem);

/**
 * @summary Create a book
 */
export const CreateBookBody = zod.object({
  title: zod.string(),
  author: zod.string(),
  isbn: zod.string().nullish(),
  category: zod.string().nullish(),
  description: zod.string().nullish(),
  year: zod.number().nullish(),
  publisher: zod.string().nullish(),
  quantity: zod.number(),
  available: zod.number(),
});

/**
 * @summary Get a book by ID
 */
export const GetBookParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBookResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  author: zod.string(),
  isbn: zod.string().nullish(),
  category: zod.string().nullish(),
  description: zod.string().nullish(),
  year: zod.number().nullish(),
  publisher: zod.string().nullish(),
  quantity: zod.number(),
  available: zod.number(),
  createdAt: zod.string().nullish(),
});

/**
 * @summary Update a book
 */
export const UpdateBookParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBookBody = zod.object({
  title: zod.string(),
  author: zod.string(),
  isbn: zod.string().nullish(),
  category: zod.string().nullish(),
  description: zod.string().nullish(),
  year: zod.number().nullish(),
  publisher: zod.string().nullish(),
  quantity: zod.number(),
  available: zod.number(),
});

export const UpdateBookResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  author: zod.string(),
  isbn: zod.string().nullish(),
  category: zod.string().nullish(),
  description: zod.string().nullish(),
  year: zod.number().nullish(),
  publisher: zod.string().nullish(),
  quantity: zod.number(),
  available: zod.number(),
  createdAt: zod.string().nullish(),
});

/**
 * @summary Delete a book
 */
export const DeleteBookParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteBookResponse = zod.object({
  success: zod.boolean(),
  message: zod.string().optional(),
});

/**
 * @summary List all users (alunos)
 */
export const ListUsersResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  role: zod.string(),
  matricula: zod.string().nullish(),
  createdAt: zod.string().nullish(),
});
export const ListUsersResponse = zod.array(ListUsersResponseItem);

/**
 * @summary Create a user
 */
export const createUserBodyRoleDefault = `aluno`;

export const CreateUserBody = zod.object({
  name: zod.string(),
  email: zod.string(),
  password: zod.string(),
  role: zod.string().default(createUserBodyRoleDefault),
  matricula: zod.string().nullish(),
});

/**
 * @summary Get a user by ID
 */
export const GetUserParams = zod.object({
  id: zod.coerce.number(),
});

export const GetUserResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  role: zod.string(),
  matricula: zod.string().nullish(),
  createdAt: zod.string().nullish(),
});

/**
 * @summary Update a user
 */
export const UpdateUserParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateUserBody = zod.object({
  name: zod.string().optional(),
  email: zod.string().optional(),
  matricula: zod.string().nullish(),
});

export const UpdateUserResponse = zod.object({
  id: zod.number(),
  name: zod.string(),
  email: zod.string(),
  role: zod.string(),
  matricula: zod.string().nullish(),
  createdAt: zod.string().nullish(),
});

/**
 * @summary Delete a user
 */
export const DeleteUserParams = zod.object({
  id: zod.coerce.number(),
});

export const DeleteUserResponse = zod.object({
  success: zod.boolean(),
  message: zod.string().optional(),
});

/**
 * @summary List all loans
 */
export const ListLoansResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  bookId: zod.number(),
  loanDate: zod.string().nullish(),
  pickupDate: zod.string().nullish(),
  dueDate: zod.string(),
  returnDate: zod.string().nullish(),
  status: zod.string(),
  fine: zod.string().nullish(),
  finePaid: zod.boolean().nullish(),
  user: zod
    .object({
      id: zod.number(),
      name: zod.string(),
      email: zod.string(),
      role: zod.string(),
      matricula: zod.string().nullish(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
  book: zod
    .object({
      id: zod.number(),
      title: zod.string(),
      author: zod.string(),
      isbn: zod.string().nullish(),
      category: zod.string().nullish(),
      description: zod.string().nullish(),
      year: zod.number().nullish(),
      publisher: zod.string().nullish(),
      quantity: zod.number(),
      available: zod.number(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
});
export const ListLoansResponse = zod.array(ListLoansResponseItem);

/**
 * @summary Create a loan
 */
export const CreateLoanBody = zod.object({
  userId: zod.number().nullish(),
  bookId: zod.number(),
  pickupDate: zod.string().nullish(),
  dueDate: zod.string(),
});

/**
 * @summary Get a loan by ID
 */
export const GetLoanParams = zod.object({
  id: zod.coerce.number(),
});

export const GetLoanResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  bookId: zod.number(),
  loanDate: zod.string().nullish(),
  pickupDate: zod.string().nullish(),
  dueDate: zod.string(),
  returnDate: zod.string().nullish(),
  status: zod.string(),
  fine: zod.string().nullish(),
  finePaid: zod.boolean().nullish(),
  user: zod
    .object({
      id: zod.number(),
      name: zod.string(),
      email: zod.string(),
      role: zod.string(),
      matricula: zod.string().nullish(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
  book: zod
    .object({
      id: zod.number(),
      title: zod.string(),
      author: zod.string(),
      isbn: zod.string().nullish(),
      category: zod.string().nullish(),
      description: zod.string().nullish(),
      year: zod.number().nullish(),
      publisher: zod.string().nullish(),
      quantity: zod.number(),
      available: zod.number(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
});

/**
 * @summary Update a loan (return, pay fine)
 */
export const UpdateLoanParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateLoanBody = zod.object({
  status: zod.string().optional(),
  pickupDate: zod.string().nullish(),
  returnDate: zod.string().nullish(),
  fine: zod.string().nullish(),
  finePaid: zod.boolean().nullish(),
});

export const UpdateLoanResponse = zod.object({
  id: zod.number(),
  userId: zod.number(),
  bookId: zod.number(),
  loanDate: zod.string().nullish(),
  pickupDate: zod.string().nullish(),
  dueDate: zod.string(),
  returnDate: zod.string().nullish(),
  status: zod.string(),
  fine: zod.string().nullish(),
  finePaid: zod.boolean().nullish(),
  user: zod
    .object({
      id: zod.number(),
      name: zod.string(),
      email: zod.string(),
      role: zod.string(),
      matricula: zod.string().nullish(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
  book: zod
    .object({
      id: zod.number(),
      title: zod.string(),
      author: zod.string(),
      isbn: zod.string().nullish(),
      category: zod.string().nullish(),
      description: zod.string().nullish(),
      year: zod.number().nullish(),
      publisher: zod.string().nullish(),
      quantity: zod.number(),
      available: zod.number(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
});

/**
 * @summary Get current user loans
 */
export const GetMyLoansResponseItem = zod.object({
  id: zod.number(),
  userId: zod.number(),
  bookId: zod.number(),
  loanDate: zod.string().nullish(),
  pickupDate: zod.string().nullish(),
  dueDate: zod.string(),
  returnDate: zod.string().nullish(),
  status: zod.string(),
  fine: zod.string().nullish(),
  finePaid: zod.boolean().nullish(),
  user: zod
    .object({
      id: zod.number(),
      name: zod.string(),
      email: zod.string(),
      role: zod.string(),
      matricula: zod.string().nullish(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
  book: zod
    .object({
      id: zod.number(),
      title: zod.string(),
      author: zod.string(),
      isbn: zod.string().nullish(),
      category: zod.string().nullish(),
      description: zod.string().nullish(),
      year: zod.number().nullish(),
      publisher: zod.string().nullish(),
      quantity: zod.number(),
      available: zod.number(),
      createdAt: zod.string().nullish(),
    })
    .nullish(),
});
export const GetMyLoansResponse = zod.array(GetMyLoansResponseItem);
