/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Sistema de Biblioteca Escolar API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateBookRequest {
  title: string;
  author: string;
  isbn?: string | null;
  category?: string | null;
  description?: string | null;
  year?: number | null;
  publisher?: string | null;
  quantity: number;
  available: number;
}
