/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Sistema de Biblioteca Escolar API
 * OpenAPI spec version: 0.1.0
 */

export interface CreateLoanRequest {
  userId?: number | null;
  bookId: number;
  pickupDate?: string | null;
  dueDate: string;
}
