/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Sistema de Biblioteca Escolar API
 * OpenAPI spec version: 0.1.0
 */
import type { Book } from "./book";
import type { User } from "./user";

export interface Loan {
  id: number;
  userId: number;
  bookId: number;
  loanDate?: string | null;
  pickupDate?: string | null;
  dueDate: string;
  returnDate?: string | null;
  status: string;
  fine?: string | null;
  finePaid?: boolean | null;
  user?: User | null;
  book?: Book | null;
}
