/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Sistema de Biblioteca Escolar API
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateLoanRequest {
  status?: string;
  pickupDate?: string | null;
  returnDate?: string | null;
  fine?: string | null;
  finePaid?: boolean | null;
}
